# Generated by Django 3.2.8 on 2022-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=25, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
